# Generated by Django 2.2.15 on 2021-10-30 06:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefecture_name', models.CharField(max_length=32, verbose_name='都道府県')),
                ('prefecture_kana', models.CharField(max_length=32, verbose_name='都道府県カナ')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 10, 30, 15, 23, 38, 328432), verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除フラグ')),
            ],
            options={
                'verbose_name': '都道府県マスタ',
                'verbose_name_plural': '都道府県マスタ',
                'db_table': 'm_prefecture',
            },
        ),
    ]
