# Generated by Django 2.2.15 on 2021-11-14 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prefecture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prefecture',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 14, 18, 43, 53, 532643), verbose_name='登録日時'),
        ),
    ]
