# Generated by Django 2.2.15 on 2021-05-12 02:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='カテゴリー名')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 5, 12, 11, 21, 26, 352025), verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除フラグ')),
            ],
            options={
                'verbose_name': 'カテゴリーマスタ',
                'verbose_name_plural': 'カテゴリーマスタ',
                'db_table': 'm_category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='商品名')),
                ('price', models.IntegerField(verbose_name='販売価格')),
                ('is_publish', models.IntegerField(verbose_name='公開ステータス')),
                ('image', models.CharField(default='no-image.jpg', max_length=255, verbose_name='商品画像')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 5, 12, 11, 21, 26, 352875), verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除フラグ')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductCategory', verbose_name='カテゴリー')),
            ],
            options={
                'verbose_name': '商品マスタ',
                'verbose_name_plural': '商品マスタ',
                'db_table': 'm_product',
            },
        ),
    ]
