# Generated by Django 2.2.15 on 2021-08-22 04:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210706_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category', verbose_name='カテゴリー'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 22, 13, 34, 0, 681163), verbose_name='登録日時'),
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
