# Generated by Django 2.2.15 on 2021-11-23 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210822_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 23, 20, 4, 20, 308331), verbose_name='登録日時'),
        ),
    ]
