# Generated by Django 2.2.15 on 2021-08-22 04:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='カテゴリー名')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 8, 22, 13, 34, 0, 678124), verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除フラグ')),
            ],
            options={
                'verbose_name': 'カテゴリーマスタ',
                'verbose_name_plural': 'カテゴリーマスタ',
                'db_table': 'm_category',
            },
        ),
    ]
