# Generated by Django 2.2.15 on 2021-08-22 04:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 22, 13, 53, 24, 113449), verbose_name='登録日時'),
        ),
    ]
