# Generated by Django 2.2.15 on 2021-11-14 09:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prefecture', '0002_auto_20211114_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='お名前')),
                ('name_kana', models.CharField(max_length=255, verbose_name='フリガナ')),
                ('email_address', models.CharField(max_length=255, verbose_name='メールアドレス')),
                ('phone_number', models.CharField(max_length=13, verbose_name='電話番号')),
                ('postal_code', models.CharField(max_length=7, verbose_name='郵便番号')),
                ('municipality', models.CharField(max_length=255, verbose_name='市区町村')),
                ('address', models.CharField(max_length=255, verbose_name='住所')),
                ('member_code', models.IntegerField(verbose_name='会員コード')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 11, 14, 18, 43, 53, 533546), verbose_name='登録日時')),
                ('prefecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prefecture.Prefecture', verbose_name='都道府県')),
            ],
            options={
                'verbose_name': '注文者情報',
                'verbose_name_plural': '注文者情報',
                'db_table': 't_sales',
            },
        ),
        migrations.CreateModel(
            name='SalesDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(verbose_name='商品ID')),
                ('price', models.IntegerField(verbose_name='価格')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 11, 14, 18, 43, 53, 534318), verbose_name='登録日時')),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Sales', verbose_name='注文者情報')),
            ],
            options={
                'verbose_name': '注文明細情報',
                'verbose_name_plural': '注文明細情報',
                'db_table': 't_sales_details',
            },
        ),
    ]
