# Generated by Django 2.2.15 on 2021-11-23 11:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20211123_2005'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesdetails',
            name='product_id',
        ),
        migrations.AddField(
            model_name='salesdetails',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='商品ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sales',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 23, 20, 4, 20, 310254), verbose_name='登録日時'),
        ),
        migrations.AlterField(
            model_name='salesdetails',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 23, 20, 4, 20, 310889), verbose_name='登録日時'),
        ),
    ]
