# Generated by Django 2.2.15 on 2021-05-25 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, verbose_name='スタッフコード')),
                ('name', models.CharField(max_length=255, verbose_name='スタッフ名')),
                ('password', models.CharField(max_length=255, verbose_name='パスワード')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 5, 25, 21, 40, 1, 549821), verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='削除フラグ')),
            ],
            options={
                'verbose_name': 'スタッフマスタ',
                'verbose_name_plural': 'スタッフマスタ',
                'db_table': 'm_staff',
            },
        ),
    ]
