# Generated by Django 2.2.15 on 2021-07-06 05:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 6, 14, 18, 10, 581009), verbose_name='登録日時'),
        ),
    ]
